name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go Program
        run: go build -o bin/main ./main

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lambda-package
          path: bin/main

      - name: Deploy to AWS Lambda
        uses: appleboy/aws-action@v0.3.0
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Change this to your AWS region
          function_name: my-lambda-function  # Change this to your Lambda function name
          zip_file: main
